---
#- hosts: tag_Name_test
  #connection: local
  # remote_user: ubuntu
  #become: true
  #tasks:

     - name: Check that the /home/distros folder exists
       stat:
         path={{ tomcat_source }}
       register: stat_result

     - name: Create the file, if it doesnt exist already
       file:
         path={{ tomcat_source }}
         state=directory
       when: not stat_result.stat.exists

     - name: Fetch Java version
       shell: java -version 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'                                                                                                                                   
       changed_when: False
       register: java_result
       failed_when: false
     - debug:
         msg: "{{ java_result.stdout }}"
       when: java_result.rc==0
       #- debug:
         #- name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
         #apt:
         # update_cache: yes
         #cache_valid_time: 3600
         # when: not java_result.stat.exists

     - name: Install java
       apt:
         update_cache: yes 
         name: openjdk-8-jdk
       when: java_result.rc!=0

     - name: Check that the download tomcat exists
       stat:
         path={{ tomcat_source }}/apache-tomcat-8.5.57
       register: stat_result1

     - name: Copy Tomcat tar file from local to remote
       copy:
         src=apache-tomcat-8.5.57.tar.gz
         dest={{ tomcat_source }} 
       when: "not stat_result1.stat.exists"
    
     - name: Check that the apache-tomcat-8.5.57 exists
       stat:
         path={{ tomcat_source }}/apache-tomcat-8.5.57
       register: stat_result

     - name: Extract the Tomcat
       unarchive:
        src={{ tomcat_source }}/apache-tomcat-8.5.57.tar.gz
        dest={{ tomcat_source }}
        remote_src=yes
       when: "not stat_result1.stat.exists"

     - name: Check that the tomcat.service exists
       stat:
         path: /etc/systemd/system/tomcat.service
       register: stat_result

     - name: Copy Tomcat service from local to remote
       copy:
         src: tomcat.service
         dest: /etc/systemd/system/
         mode: 0755
       when: "not stat_result1.stat.exists"

     - name: Start and enable Tomcat service
       systemd:
         name: tomcat
         state: started
         # enabled: true
         daemon_reload: true
