---
- hosts: tag_Name_master-tomcatserver
  #connection: local
  remote_user: ubuntu
  become: true
  tasks:

     - name: Check that the /home/tomcat folder exists
       stat:
         path: /home/tomcat
       register: stat_result

     - name: Create the file, if it doesnt exist already
       file:
         path: /home/tomcat
         state: directory
       when: not stat_result.stat.exists

     - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
       apt:
         update_cache: yes
         cache_valid_time: 3600

     - name: Install Maven
       apt: name={{item}} state=present update_cache=yes
       with_items:
         - maven
         - openjdk-8-jdk

     - name: Check that the download tomcat exists
       stat:
         path: /home/tomcat/apache-tomcat-8.5.57.tar.gz
       register: stat_result1

     - name: download file with custom HTTP headers
       get_url:
         url: http://apachemirror.wuchna.com/tomcat/tomcat-8/v8.5.57/bin/apache-tomcat-8.5.57.tar.gz
         dest: /home/distros
       when: not stat_result1.stat.exists

     - name: Extract the Tomcat
       unarchive:
         src: /home/tomcat/apache-tomcat-8.5.57.tar.gz
         dest: /home/tomcat
         remote_src: yes




